---
#
- name: prepare elasticsearch group
  group: name=elasticsearch state=present

- name: prepare elasticsearch user
  user: name=elasticsearch group=elasticsearch

- name: prepare elasticsearch directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "elasticsearch"
    group: "elasticsearch"
  with_items:
    - "{{ elasticsearch_home }}"
    - "{{ elasticsearch_data }}"
    - "{{ elasticsearch_logs }}"

- name: define logging
  template: src=logging.yml.j2 dest=/etc/elasticsearch/logging.yml

- name: define elasticsearch node
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml

# - name: reload systemd
#   command: systemctl daemon-reload
#   when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

# - name: reload systemd
#   command: systemctl daemon-reload
#   when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: start and enable elasticsearch service
  service: name=elasticsearch enabled=yes state=started
