---
#
- name: define logging
  template: src=logging.yml.j2 dest=/etc/elasticsearch/logging.yml

- name: define elasticsearch node
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml

- name: reload systemd
  become: yes
  become_user: "root"
  command: systemctl daemon-reload

- name: start and enable elasticsearch service
  service: name=elasticsearch enabled=yes state=started
