---
#
- name: define repo
  template:
    src: elasticsearch-yum.repo.j2
    dest: "/etc/yum.repos.d/elasticsearch-{{ elasticsearch_major }}.x.repo"

- name: import elastic key
  rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch

- name: install elasticsearch
  yum: name=elasticsearch state=present
