---
#
- name: prepare elasticsearch group
  group:
    name: elasticsearch
    state: present

- name: prepare elasticsearch user
  user:
    name: elasticsearch
    group: elasticsearch
    state: present
